### ISSUE TITLE
Add Pids() method

### ISSUE THREAD

**Issue by vtolstov** [mitchellh/go-ps#4]
I have handmade linux implementation that for specific pid returns it child pids.
Also i'm using serach by process name to get all pids for this process name mask.
I can create pr for this (start from linux and may be freebsd) does it will be useful ?

**Comment by vtolstov** [comment]
check pr #6

**Comment by vbmade2000** [comment]
@vtolstov  Can this be closed ?

**Comment by vbmade2000** [comment]
@vtolstov  Can this be closed ?

**Comment by vtolstov** [comment]
sorry, yes, this can be closed.
